apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stedi-lucas
spec:
  selector:
    matchLabels:
      app: redis-stedi-lucas # must match spec.template.metadata.lebels
  serviceName: redis-stedi-lucas
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-stedi-lucas
    spec:
      containers:
        - name: redis-stedi-lucas
          image: redis:7.0.5-alpine
          imagePullPolicy: Always
          args: [ "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes", "--save", "900", "1", "--save", "30", "2" ]
          ports:
            - containerPort: 6379
              name: redis
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secrets-lucas
                key: REDIS_PASSWORD
          volumeMounts:
            - name: redis-lucas-volume
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-lucas-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-stedi-lucas
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis-stedi-lucas
